---
# default dockerd daemon json configuration options ----------------------------------------
## https://docs.docker.com/engine/reference/commandline/dockerd

#docker_config_insecure_registries:
#   - "10.132.0.18:5000"
docker_default_runtime: "nvidia"
runtimes_nvidia_path: "/usr/bin/nvidia-container-runtime"
runtimes_nvidia_runtimeArgs: []
#docker_config_graph: "/var/lib/docker"
#docker_config_log_driver: ""
docker_config_log_opts: 1g
#docker_config_max_concurrent_downloads: 3
#docker_config_max_concurrent_uploads: 5
#docker_config_log_level: ""
#docker_config_debug: false
#docker_config_hosts:
#  - "unix:///var/run/docker.sock"
#docker_config_bridge: ""
#docker_config_bip: "172.16.0.1/24"
#docker_config_fixed_cidr: "172.16.0.0/24"
#docker_config_fixed_cidr_v6: ""
#docker_config_default_gateway: ""
#docker_config_default_gateway_v6: ""
#docker_config_selinux_enabled: false
#docker_config_ip: "0.0.0.0"
#docker_config_group: "docker"

#docker_config_tls: ~
#docker_config_tlsverify: ~
#docker_config_tlscacert: ""
#docker_config_tlscert: ""
#docker_config_tlskey: ""


# ==============================================================================
# dictionary of common configuration options  ----------------------------------
# ==============================================================================
docker_config_common:
#  "insecure-registries": "{{ docker_config_insecure_registries }}"
  "default-runtime": "{{ docker_default_runtime }}"
  "runtimes":
    "nvidia":
      "path": "{{ runtimes_nvidia_path }}"
      "runtimeArgs": "{{ runtimes_nvidia_runtimeArgs }}"
#  "log-driver": "{{ docker_config_log_driver }}"
  "log-opts":
    "max-size": "{{ docker_config_log_opts }}"
#  "graph": "{{ docker_config_graph }}"
#  "max-concurrent-downloads": "{{ docker_config_max_concurrent_downloads }}"
#  "max-concurrent-uploads": "{{ docker_config_max_concurrent_uploads }}"
#  "debug": "{{ docker_config_debug }}"
#  "hosts": "{{ docker_config_hosts }}"
#  "log-level": "{{ docker_config_log_level }}"
#  "selinux-enabled": "{{ docker_config_selinux_enabled }}"
#  "group": "{{ docker_config_group }}"
#  "bridge": "{{ docker_config_bridge }}"
#  "bip": "{{ docker_config_bip }}"
#  "fixed-cidr": "{{ docker_config_fixed_cidr }}"
#  "fixed-cidr-v6": "{{ docker_config_fixed_cidr_v6 }}"
#  "default-gateway": "{{ docker_config_default_gateway }}"
#  "default-gateway-v6": "{{ docker_config_default_gateway_v6 }}"
#
#  "ip": "{{ docker_config_ip }}"

# ==============================================================================
# dictionary for extra/custom settings that can be added -----------------------
# ==============================================================================
# https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file
docker_config_custom: {}
