---
# Log-level
cilium_debug: false

# IP configuration
cilium_enable_ipv4: true
cilium_enable_ipv6: false

# Etcd SSL dirs
cilium_cert_dir: /etc/cilium/certs

# Cilium Network Policy directory
cilium_policy_dir: /etc/kubernetes/policy

# Optional features
cilium_enable_prometheus: false

## Clustering
cilium_cluster_name: cluster-1
cilium_cluster_id: 1
