---
- name: install epel-release-latest 7
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install cuda-repo-rhel7 yum repo
  yum:
    name: "{{nvidia_cuda_repo}}/{{short_name_redhat}}{{ansible_distribution_major_version}}/{{ansible_architecture}}/cuda-repo-{{short_name_redhat}}{{ansible_distribution_major_version}}-{{cuda_version}}.{{ansible_architecture}}.rpm"
    state: present

- name: install mesa-libGL
  shell: yum install mesa-libGL -y
#    update_cache: yes


- name: get if redhat os is workstation
  shell: cat /etc/redhat-release 
  register: get_os_version


- name: add yum repo rhel-7-server-optional-rpms on Redhat server
  shell: subscription-manager repos --enable=rhel-7-server-optional-rpms 
  when: (get_os_version is defined) and (get_os_version.stdout.find('Workstation') == -1) and (ansible_distribution == "RedHat")

- name: add yum repo rhel-7-workstation-optional-rpms on Redhat workstation
  shell: subscription-manager repos --enable=rhel-7-workstation-optional-rpms
  when: (get_os_version is defined) and (get_os_version.stdout.find('Workstation') != -1) and (ansible_distribution == "RedHat")


- name: install prerequisites packages for cuda-driver on Redhat workstation
  shell: yum -y install kernel-devel-$(uname -r) kernel-header-$(uname -r) gcc make dkms epel-release
  when: (get_os_version is defined) and (get_os_version.stdout.find('Workstation') != -1) and (ansible_distribution == "RedHat")


- name: install cuda-driver
  yum:
    name: cuda-driver
    state: present
    update_cache: yes
  notify: Reboot node
  #when: (get_os_version is defined) and (get_os_version.stdout.find('Workstation') == -1)

#- name: install cuda-driver 410 on redhat workstation
#  yum:
#    name:
#      - cuda-drivers-410.79-1.x86_64
#      - nvidia-modprobe-410.79-1.el7.x86_64
#      - nvidia-driver-NVML-410.79-1.el7.x86_64
#      - nvidia-driver-cuda-410.79-1.el7.x86_64
#      - nvidia-libXNVCtrl-devel-410.79-1.el7.x86_64
#      - nvidia-driver-410.79-1.el7.x86_64
#      - nvidia-driver-cuda-libs-410.79-1.el7.x86_64
#      - dkms-nvidia-410.79-1.el7.x86_64
#      - nvidia-driver-NvFBCOpenGL-410.79-1.el7.x86_64
#      - nvidia-xconfig-410.79-1.el7.x86_64
#      - nvidia-driver-devel-410.79-1.el7.x86_64
##      - libnvidia-container-tools-1.0.1-1.x86_64
#      - nvidia-libXNVCtrl-410.79-1.el7.x86_64
#      - nvidia-settings-410.79-1.el7.x86_64
#      - nvidia-persistenced-410.79-1.el7.x86_64
#      - nvidia-driver-libs-410.79-1.el7.x86_64
#    state: present
#    update_cache: yes
#  when: (get_os_version is defined) and (get_os_version.stdout.find('Workstation') != -1) and (ansible_distribution == "RedHat")
