---
- name: Add an Apt signing key
  shell: apt-key adv --fetch-keys {{nvidia_cuda_repo}}/{{ ansible_distribution|lower }}{{ansible_distribution_major_version}}{{distribution_minor.stdout}}/{{ansible_architecture}}/7fa2af80.pub
  when: (airgap != true)
#  apt_key:
#    url: {{nvidia_cuda_repo}}/{{ ansible_distribution|lower }}{{ansible_distribution_major_version}}{{distribution_minor.stdout}}/{{ansible_architecture}}
#    state: present

- name: Add repository with recent GPU drivers
  apt_repository:
    repo: "deb {{nvidia_cuda_repo}}/{{ ansible_distribution|lower }}{{ansible_distribution_major_version}}{{distribution_minor.stdout}}/{{ansible_architecture}} /"
  when: (airgap != true)

- name: Install NVIDIA drivers and cuda packages
  apt:
    pkg: cuda-drivers
    state: present
    install_recommends: no
    update_cache: yes
