- name: restart docker
  service:
    name: docker
    enabled: yes
    state: restarted
  become: yes

- name: reload systemd docker
  systemd:
    daemon_reload: yes
    name: docker
  #notify: restart docker
