  - name: Install necessary packages (ubuntu/debian)
    apt:
      name:
        - gcc
        - make
        - kmod
        - pciutils
        - wget
      state: present
      update_cache: yes

  - name: Install kernel headers package (debian)
    shell: apt install -y linux-headers-$(uname -r|sed 's/[^-]*-[^-]*-//')
