  - name: Install epel-release repository (rhel/centos)
    yum:
      name: epel-release
      state: latest
      update_cache: yes

  - name: Install necessary packages (rhel/centos)
    yum:
      name:
        - gcc
        - make
        - kmod
        - pciutils
        - wget
        - dkms
        - kernel-devel
      state: present
      update_cache: yes
    
  - name: Install kernel headers package (debian)
    shell: yum install -y kernel-devel-$(uname -r) kernel-header-$(uname -r)
